database:
    driver:     pdo_mysql
    host:       localhost
    port:       ~
    dbname:     
    user:       root
    password:   ~
    charset:    utf8

mailer:
    host:       127.0.0.1
    username:   
    password:   
    port:       465
    encryption: ssl
    auth_mode:  smtp

locale:         en
secret:         ThisTokenIsNotSoSecretChangeIt