mailer:
    subject: Mensaje desde la página web
    body: >
        <html>
         <head></head>
         <body>Hola:

        Nombre:  %s
        Telefono: %s
        Email: %s
        Escribió la siguiente consulta:
        %s

        Que tenga un buen dia.
         </body>
        </html>

admin:
    responses:
        